#!/usr/bin/env python3
"""Generate C++ and Python protocol bindings from the schema.

Runs at build time on a development machine or in CI. Never deployed to the robot, never
runs on the MCU, contributes no code size and no runtime dependency. See
docs/decisions/0003-schema-format-and-code-generation.md.

Output is deterministic: the same schema always produces byte-identical files, which is
what lets tests/python/test_generator.py pin the output and turn a generator change into a
reviewable diff instead of a silent one.

Usage:
    python3 protocol/generate.py [--out-dir protocol/generated] [--check]

    --check  regenerate into memory and exit non-zero if the files on disk differ.
             Used by CI and by the golden-output test.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from schema_loader import (  # noqa: E402
    CRC_BYTES,
    HEADER_BYTES,
    Enum,
    Field,
    Message,
    SCALAR_SIZES,
    Schema,
    SchemaError,
    default_schema_paths,
    load_schema,
)

BANNER_LINES = [
    "AUTO-GENERATED by protocol/generate.py from protocol/schema/*.yaml.",
    "DO NOT EDIT. Edit the schema and regenerate.",
    "",
    "The schema is the single source of truth (CLAUDE.md). This file is gitignored so that",
    "editing it is impossible to mistake for editing the protocol.",
]

# struct module format characters, little-endian.
PY_FORMAT = {"u8": "B", "u16": "H", "u32": "I", "i8": "b", "i16": "h", "i32": "i", "f32": "f"}
CPP_TYPE = {"u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t",
            "i8": "int8_t", "i16": "int16_t", "i32": "int32_t", "f32": "float"}
PY_TYPE = {"u8": "int", "u16": "int", "u32": "int", "i8": "int", "i16": "int",
           "i32": "int", "f32": "float"}


def cpp_banner() -> str:
    return "\n".join(f"// {line}".rstrip() for line in BANNER_LINES)


def py_banner() -> str:
    return '"""' + "\n".join(BANNER_LINES) + '\n"""'


def field_scalar(f: Field, enums: dict[str, Enum]) -> str:
    scalar = f.scalar_type(enums)
    assert scalar is not None, "schema was validated, so every type resolves"
    return scalar


# --------------------------------------------------------------------------------- C++

def cpp_enum(e: Enum) -> str:
    out = [f"/// {e.description}" if e.description else "",
           f"enum class {e.name} : {CPP_TYPE[e.underlying]} {{"]
    for v in e.values:
        out.append(f"  {v.name} = {v.value},")
    out.append("};")
    out.append("")
    out.append(f"/// True if `value` is one of {e.name}'s declared values.")
    out.append(f"constexpr bool is_valid_{_snake(e.name)}({CPP_TYPE[e.underlying]} value) {{")
    out.append("  return " + "\n      || ".join(
        f"value == {v.value}" for v in e.values) + ";")
    out.append("}")
    return "\n".join(line for line in out if line != "" or True)


def _snake(name: str) -> str:
    out: list[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0 and not name[i - 1].isupper():
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def cpp_field_decl(f: Field, enums: dict[str, Enum]) -> list[str]:
    lines: list[str] = []
    doc = []
    if f.description:
        doc.append(f.description)
    if f.unit:
        doc.append(f"Unit: {f.unit}.")
    if f.range:
        doc.append(f"Range: [{f.range[0]}, {f.range[1]}].")
    if f.source:
        doc.append(f"Source: {f.source}")
    if f.const is not None:
        doc.append(f"Must equal 0x{f.const:08X}.")
    for line in doc:
        lines.append(f"  /// {line}")

    ctype = f.enum if f.type == "enum" else CPP_TYPE[f.type]
    if f.count > 1:
        lines.append(f"  {ctype} {f.name}[{f.count}] = {{}};")
    elif f.type == "enum":
        first = enums[f.enum].values[0].name
        lines.append(f"  {ctype} {f.name} = {ctype}::{first};")
    elif f.type in ("f32",):
        lines.append(f"  {ctype} {f.name} = 0.0F;")
    else:
        lines.append(f"  {ctype} {f.name} = 0;")
    return lines


def cpp_encode_field(f: Field, enums: dict[str, Enum], offset: int) -> tuple[list[str], int]:
    scalar = field_scalar(f, enums)
    size = SCALAR_SIZES[scalar]
    lines: list[str] = []
    if f.count > 1:
        lines.append(f"  for (size_t i = 0; i < {f.count}; ++i) {{")
        lines.append(f"    detail::write_{scalar}(out + {offset} + i * {size}, {f.name}[i]);")
        lines.append("  }")
    elif f.type == "enum":
        lines.append(f"  detail::write_{scalar}(out + {offset}, "
                     f"static_cast<{CPP_TYPE[scalar]}>({f.name}));")
    else:
        lines.append(f"  detail::write_{scalar}(out + {offset}, {f.name});")
    return lines, offset + size * f.count


def cpp_decode_field(f: Field, enums: dict[str, Enum], offset: int) -> tuple[list[str], int]:
    scalar = field_scalar(f, enums)
    size = SCALAR_SIZES[scalar]
    lines: list[str] = []
    if f.count > 1:
        lines.append(f"  for (size_t i = 0; i < {f.count}; ++i) {{")
        lines.append(f"    out.{f.name}[i] = detail::read_{scalar}(in + {offset} + i * {size});")
        lines.append("  }")
    elif f.type == "enum":
        lines.append(f"  const {CPP_TYPE[scalar]} raw_{f.name} = "
                     f"detail::read_{scalar}(in + {offset});")
        lines.append(f"  if (!is_valid_{_snake(f.enum)}(raw_{f.name})) {{")
        lines.append("    return false;  // undeclared enum value")
        lines.append("  }")
        lines.append(f"  out.{f.name} = static_cast<{f.enum}>(raw_{f.name});")
    else:
        lines.append(f"  out.{f.name} = detail::read_{scalar}(in + {offset});")
    return lines, offset + size * f.count


def cpp_message(m: Message, enums: dict[str, Enum]) -> str:
    payload = m.payload_bytes(enums)
    lines: list[str] = []
    for line in (m.description or "").splitlines():
        lines.append(f"/// {line.strip()}".rstrip())
    if m.rate_hz:
        lines.append(f"/// Nominal rate: {m.rate_hz} Hz.")
    lines.append(f"/// Direction: {m.direction}. Payload: {payload} bytes.")
    lines.append(f"struct {m.name} {{")
    lines.append(f"  static constexpr MessageId kId = MessageId::{m.name};")
    lines.append(f"  static constexpr size_t kPayloadBytes = {payload};")
    lines.append("")

    ranged = [f for f in m.fields if f.range is not None]
    if ranged:
        lines.append("  /// Declared limits from the schema. Decoding rejects anything outside.")
        lines.append("  struct Limits {")
        for f in ranged:
            scalar = field_scalar(f, enums)
            suffix = "F" if scalar == "f32" else ""
            lo, hi = f.range
            fmt = (lambda v: f"{v}{suffix}") if scalar == "f32" else (lambda v: f"{int(v)}")
            lines.append(f"    static constexpr {CPP_TYPE[scalar]} {f.name}_min = {fmt(lo)};")
            lines.append(f"    static constexpr {CPP_TYPE[scalar]} {f.name}_max = {fmt(hi)};")
        lines.append("  };")
        lines.append("")

    for f in m.fields:
        lines.extend(cpp_field_decl(f, enums))
    if m.fields:
        lines.append("")

    # in_range
    lines.append("  /// True if every ranged field is inside its declared limits.")
    lines.append("  ///")
    lines.append("  /// NaN fails this check, because NaN compares false against both bounds.")
    lines.append("  /// That is deliberate: a NaN command must never reach a control loop.")
    lines.append("  bool in_range() const {")
    if ranged:
        conds = []
        for f in ranged:
            conds.append(f"({f.name} >= Limits::{f.name}_min "
                         f"&& {f.name} <= Limits::{f.name}_max)")
        lines.append("    return " + "\n        && ".join(conds) + ";")
    else:
        lines.append("    return true;  // no ranged fields")
    lines.append("  }")
    lines.append("")

    consts = [f for f in m.fields if f.const is not None]
    lines.append("  /// True if every `const`-declared field carries its required value.")
    lines.append("  bool magic_ok() const {")
    if consts:
        lines.append("    return " + "\n        && ".join(
            f"{f.name} == 0x{f.const:08X}U" for f in consts) + ";")
    else:
        lines.append("    return true;  // no magic constants")
    lines.append("  }")
    lines.append("")

    lines.append("  /// Serializes the payload little-endian into `out`, which must have")
    lines.append("  /// room for kPayloadBytes. Returns the number of bytes written.")
    lines.append("  size_t encode(uint8_t* out) const {")
    if not m.fields:
        lines.append("    (void)out;")
    offset = 0
    for f in m.fields:
        body, offset = cpp_encode_field(f, enums, offset)
        lines.extend("  " + line.lstrip() if False else line for line in body)
    assert offset == payload, f"{m.name}: encode wrote {offset}, expected {payload}"
    lines.append("    return kPayloadBytes;")
    lines.append("  }")
    lines.append("")

    lines.append("  /// Parses a payload. Returns false on wrong length, an undeclared enum")
    lines.append("  /// value, a bad magic constant, or an out-of-range field, leaving `out`")
    lines.append("  /// unspecified. No allocation, no exceptions.")
    lines.append("  static bool decode(const uint8_t* in, size_t len, "
                 f"{m.name}& out) {{")
    lines.append("    if (len != kPayloadBytes) {")
    lines.append("      return false;")
    lines.append("    }")
    if not m.fields:
        lines.append("    (void)in;")
        lines.append("    (void)out;")
    offset = 0
    for f in m.fields:
        body, offset = cpp_decode_field(f, enums, offset)
        lines.extend(body)
    lines.append("    return out.magic_ok() && out.in_range();")
    lines.append("  }")
    lines.append("};")
    return "\n".join(lines)


def generate_hpp(s: Schema) -> str:
    out: list[str] = [cpp_banner(), "", "#pragma once", "",
                      "#include <cstddef>", "#include <cstdint>", "#include <cstring>", "",
                      "namespace recon::protocol {", ""]

    out += [
        "/// Wire protocol version. Both ends must agree exactly; see docs/decisions/0002.",
        f"constexpr uint8_t kProtocolVersion = {s.protocol_version};",
        "",
        "/// version:1 + message_id:1 + seq:1 + timestamp_us:4",
        f"constexpr size_t kHeaderBytes = {HEADER_BYTES};",
        "/// CRC-32/ISO-HDLC, little-endian.",
        f"constexpr size_t kCrcBytes = {CRC_BYTES};",
        "/// Largest payload any message declares room for.",
        f"constexpr size_t kMaxPayloadBytes = {s.max_payload_bytes};",
        "/// Header + largest payload + CRC, before COBS.",
        f"constexpr size_t kMaxLogicalFrameBytes = {s.max_logical_frame_bytes};",
        "/// Worst case on the wire: COBS overhead plus the 0x00 delimiter. Firmware buffer",
        "/// sizes derive from this rather than from a written-down number.",
        f"constexpr size_t kMaxWireFrameBytes = {s.max_wire_frame_bytes};",
        "",
        "/// Message identifiers. Ranges are partitioned by direction so a corrupted id is",
        "/// more likely to be rejected than read as a legal message going the wrong way.",
    ]
    for direction, (low, high) in s.id_ranges.items():
        out.append(f"///   {direction}: [0x{low:02X}, 0x{high:02X}]")
    out.append("enum class MessageId : uint8_t {")
    for m in s.messages:
        out.append(f"  {m.name} = 0x{m.id:02X},")
    out.append("};")
    out.append("")

    for e in s.enums.values():
        out.append(cpp_enum(e))
        out.append("")

    out += [
        "namespace detail {",
        "",
        "// Explicit little-endian serialization, byte by byte. ADR 0002 requires this",
        "// rather than memcpy of a packed struct: no dependence on compiler padding, no",
        "// type punning, and no unaligned multi-byte access on the Cortex-M4.",
        "",
        "inline void write_u8(uint8_t* p, uint8_t v) { p[0] = v; }",
        "inline void write_u16(uint8_t* p, uint16_t v) {",
        "  p[0] = static_cast<uint8_t>(v & 0xFFU);",
        "  p[1] = static_cast<uint8_t>((v >> 8) & 0xFFU);",
        "}",
        "inline void write_u32(uint8_t* p, uint32_t v) {",
        "  p[0] = static_cast<uint8_t>(v & 0xFFU);",
        "  p[1] = static_cast<uint8_t>((v >> 8) & 0xFFU);",
        "  p[2] = static_cast<uint8_t>((v >> 16) & 0xFFU);",
        "  p[3] = static_cast<uint8_t>((v >> 24) & 0xFFU);",
        "}",
        "",
        "inline uint8_t read_u8(const uint8_t* p) { return p[0]; }",
        "inline uint16_t read_u16(const uint8_t* p) {",
        "  return static_cast<uint16_t>(static_cast<uint16_t>(p[0])",
        "                              | (static_cast<uint16_t>(p[1]) << 8));",
        "}",
        "inline uint32_t read_u32(const uint8_t* p) {",
        "  return static_cast<uint32_t>(p[0]) | (static_cast<uint32_t>(p[1]) << 8)",
        "       | (static_cast<uint32_t>(p[2]) << 16) | (static_cast<uint32_t>(p[3]) << 24);",
        "}",
        "",
        "// Signed and float go through memcpy of the unsigned bit pattern. A narrowing",
        "// cast from unsigned to signed is implementation-defined before C++20, and",
        "// reinterpret_cast on a float is undefined; memcpy is fully defined and compiles",
        "// to nothing on both targets.",
        "inline void write_i8(uint8_t* p, int8_t v) {",
        "  uint8_t u = 0; std::memcpy(&u, &v, sizeof(u)); write_u8(p, u);",
        "}",
        "inline void write_i16(uint8_t* p, int16_t v) {",
        "  uint16_t u = 0; std::memcpy(&u, &v, sizeof(u)); write_u16(p, u);",
        "}",
        "inline void write_i32(uint8_t* p, int32_t v) {",
        "  uint32_t u = 0; std::memcpy(&u, &v, sizeof(u)); write_u32(p, u);",
        "}",
        "inline void write_f32(uint8_t* p, float v) {",
        "  uint32_t u = 0; std::memcpy(&u, &v, sizeof(u)); write_u32(p, u);",
        "}",
        "",
        "inline int8_t read_i8(const uint8_t* p) {",
        "  const uint8_t u = read_u8(p); int8_t v = 0; std::memcpy(&v, &u, sizeof(v)); return v;",
        "}",
        "inline int16_t read_i16(const uint8_t* p) {",
        "  const uint16_t u = read_u16(p); int16_t v = 0; std::memcpy(&v, &u, sizeof(v)); return v;",
        "}",
        "inline int32_t read_i32(const uint8_t* p) {",
        "  const uint32_t u = read_u32(p); int32_t v = 0; std::memcpy(&v, &u, sizeof(v)); return v;",
        "}",
        "inline float read_f32(const uint8_t* p) {",
        "  const uint32_t u = read_u32(p); float v = 0.0F; std::memcpy(&v, &u, sizeof(v)); return v;",
        "}",
        "",
        "}  // namespace detail",
        "",
    ]

    for m in s.messages:
        out.append(cpp_message(m, s.enums))
        out.append("")

    out += [
        "/// Payload size for a message id. Returns false for an unknown id.",
        "///",
        "/// The frame decoder uses this to reject a frame whose decoded length disagrees",
        "/// with the size its id declares. That check replaces a self-reported length",
        "/// field, which could only ever disagree with reality (ADR 0002).",
        "inline bool payload_bytes_for(uint8_t id, size_t& out) {",
        "  switch (id) {",
    ]
    for m in s.messages:
        out.append(f"    case 0x{m.id:02X}: out = {m.payload_bytes(s.enums)}; return true;")
    out += [
        "    default: return false;",
        "  }",
        "}",
        "",
        "/// True if `id` is a message this schema version declares.",
        "inline bool is_known_message_id(uint8_t id) {",
        "  size_t unused = 0;",
        "  return payload_bytes_for(id, unused);",
        "}",
        "",
    ]

    if s.params:
        out += [
            "/// Tunable parameter identifiers. See protocol/schema/params.yaml.",
            "enum class ParamId : uint16_t {",
        ]
        for p in s.params:
            out.append(f"  {p.name} = 0x{p.id:04X},")
        out += ["};", ""]

    out += ["}  // namespace recon::protocol", ""]
    return "\n".join(out)


# ------------------------------------------------------------------------------ Python

def py_struct_format(m: Message, enums: dict[str, Enum]) -> str:
    fmt = "<"
    for f in m.fields:
        scalar = field_scalar(f, enums)
        if f.count > 1:
            fmt += f"{f.count}s" if scalar == "u8" else PY_FORMAT[scalar] * f.count
        else:
            fmt += PY_FORMAT[scalar]
    return fmt


def py_message(m: Message, enums: dict[str, Enum]) -> str:
    payload = m.payload_bytes(enums)
    lines = ["@dataclass", f"class {m.name}:", '    """']
    for line in (m.description or "").splitlines():
        lines.append(f"    {line.strip()}".rstrip())
    if m.rate_hz:
        lines.append(f"    Nominal rate: {m.rate_hz} Hz.")
    lines.append(f"    Direction: {m.direction}. Payload: {payload} bytes.")
    lines.append('    """')
    lines.append("")
    lines.append(f"    MESSAGE_ID: ClassVar[int] = 0x{m.id:02X}")
    lines.append(f"    PAYLOAD_BYTES: ClassVar[int] = {payload}")
    lines.append(f'    STRUCT_FORMAT: ClassVar[str] = "{py_struct_format(m, enums)}"')
    lines.append("")

    for f in m.fields:
        scalar = field_scalar(f, enums)
        if f.count > 1 and scalar == "u8":
            ann, default = "bytes", f'b"\\x00" * {f.count}'
            lines.append(f"    {f.name}: {ann} = field(default_factory=lambda: {default})")
        elif f.count > 1:
            lines.append(f"    {f.name}: tuple = field(default_factory=lambda: "
                         f"({', '.join(['0'] * f.count)},))")
        elif f.type == "enum":
            first = enums[f.enum].values[0].name
            lines.append(f"    {f.name}: {f.enum} = {f.enum}.{first}")
        else:
            zero = "0.0" if scalar == "f32" else "0"
            lines.append(f"    {f.name}: {PY_TYPE[scalar]} = {zero}")
    lines.append("")

    ranged = [f for f in m.fields if f.range is not None]
    lines.append("    LIMITS: ClassVar[dict[str, tuple[float, float]]] = {")
    for f in ranged:
        lines.append(f'        "{f.name}": ({f.range[0]}, {f.range[1]}),')
    lines.append("    }")
    lines.append("")

    consts = [f for f in m.fields if f.const is not None]
    lines.append("    MAGICS: ClassVar[dict[str, int]] = {")
    for f in consts:
        lines.append(f'        "{f.name}": 0x{f.const:08X},')
    lines.append("    }")
    lines.append("")

    lines += [
        "    def in_range(self) -> bool:",
        '        """True if every ranged field is inside its declared limits.',
        "",
        "        NaN fails, because NaN compares false against both bounds. A NaN command",
        "        must never reach a control loop.",
        '        """',
        "        for name, (low, high) in self.LIMITS.items():",
        "            value = getattr(self, name)",
        "            if not low <= value <= high:",
        "                return False",
        "        return True",
        "",
        "    def magic_ok(self) -> bool:",
        '        """True if every const-declared field carries its required value."""',
        "        return all(getattr(self, n) == v for n, v in self.MAGICS.items())",
        "",
        "    def encode(self) -> bytes:",
        '        """Serializes the payload little-endian. Exactly PAYLOAD_BYTES long."""',
        "        return struct.pack(self.STRUCT_FORMAT" +
        ("".join(f", {_py_pack_expr(f, enums)}" for f in m.fields)) + ")",
        "",
        "    @classmethod",
        f"    def decode(cls, data: bytes) -> \"{m.name}\":",
        '        """Parses a payload.',
        "",
        "        Raises ValueError on wrong length, an undeclared enum value, a bad magic",
        "        constant, or an out-of-range field.",
        '        """',
        "        if len(data) != cls.PAYLOAD_BYTES:",
        "            raise ValueError(",
        f'                f"{m.name}: expected {{cls.PAYLOAD_BYTES}} payload bytes, "',
        '                f"got {len(data)}")',
    ]
    if m.fields:
        lines.append("        values = struct.unpack(cls.STRUCT_FORMAT, data)")
        lines.append("        out = cls(")
        idx = 0
        for f in m.fields:
            scalar = field_scalar(f, enums)
            if f.count > 1 and scalar == "u8":
                lines.append(f"            {f.name}=values[{idx}],")
                idx += 1
            elif f.count > 1:
                lines.append(f"            {f.name}=tuple(values[{idx}:{idx + f.count}]),")
                idx += f.count
            elif f.type == "enum":
                lines.append(f"            {f.name}=_as_enum({f.enum}, values[{idx}], "
                             f'"{m.name}.{f.name}"),')
                idx += 1
            else:
                lines.append(f"            {f.name}=values[{idx}],")
                idx += 1
        lines.append("        )")
    else:
        lines.append("        out = cls()")
    lines += [
        "        if not out.magic_ok():",
        f'            raise ValueError("{m.name}: magic constant mismatch")',
        "        if not out.in_range():",
        f'            raise ValueError("{m.name}: field outside declared range")',
        "        return out",
    ]
    return "\n".join(lines)


def _py_pack_expr(f: Field, enums: dict[str, Enum]) -> str:
    scalar = field_scalar(f, enums)
    if f.count > 1 and scalar == "u8":
        return f"self.{f.name}"
    if f.count > 1:
        return f"*self.{f.name}"
    if f.type == "enum":
        return f"int(self.{f.name})"
    return f"self.{f.name}"


def generate_py(s: Schema) -> str:
    out = [py_banner(), "",
           "from __future__ import annotations", "",
           "import struct",
           "from dataclasses import dataclass, field",
           "from enum import IntEnum",
           "from typing import Any, ClassVar", "",
           f"PROTOCOL_VERSION = {s.protocol_version}",
           f"HEADER_BYTES = {HEADER_BYTES}",
           f"CRC_BYTES = {CRC_BYTES}",
           f"MAX_PAYLOAD_BYTES = {s.max_payload_bytes}",
           f"MAX_LOGICAL_FRAME_BYTES = {s.max_logical_frame_bytes}",
           f"MAX_WIRE_FRAME_BYTES = {s.max_wire_frame_bytes}", "",
           "",
           "def _as_enum(enum_cls: Any, value: int, where: str) -> Any:",
           '    """Converts a raw wire value to an enum, rejecting undeclared values."""',
           "    try:",
           "        return enum_cls(value)",
           "    except ValueError as exc:",
           '        raise ValueError(',
           '            f"{where}: {value} is not a declared {enum_cls.__name__} value"',
           "        ) from exc",
           "",
           "",
           "class MessageId(IntEnum):",
           ]
    for m in s.messages:
        out.append(f"    {m.name} = 0x{m.id:02X}")
    out += ["", ""]

    for e in s.enums.values():
        out.append(f"class {e.name}(IntEnum):")
        if e.description:
            out.append(f'    """{e.description}"""')
            out.append("")
        for v in e.values:
            out.append(f"    {v.name} = {v.value}")
        out += ["", ""]

    for m in s.messages:
        out.append(py_message(m, s.enums))
        out += ["", ""]

    out.append("MESSAGE_BY_ID: dict[int, type] = {")
    for m in s.messages:
        out.append(f"    0x{m.id:02X}: {m.name},")
    out += ["}", "", ""]

    out.append("PAYLOAD_BYTES_BY_ID: dict[int, int] = {")
    for m in s.messages:
        out.append(f"    0x{m.id:02X}: {m.payload_bytes(s.enums)},")
    out += ["}", "", ""]

    if s.params:
        out.append("class ParamId(IntEnum):")
        for p in s.params:
            out.append(f"    {p.name} = 0x{p.id:04X}")
        out += ["", ""]
        out.append("PARAMS: dict[int, dict[str, Any]] = {")
        for p in s.params:
            out.append(f"    0x{p.id:04X}: {{")
            out.append(f'        "name": "{p.name}",')
            out.append(f'        "type": "{p.type}",')
            out.append(f'        "unit": {p.unit!r},')
            out.append(f'        "range": ({p.range[0]}, {p.range[1]}),')
            out.append(f'        "default": {p.default},')
            out.append(f'        "writable": {p.writable},')
            out.append("    },")
        out += ["}", ""]
    return "\n".join(out)


# -------------------------------------------------------------------------------- main

def render(schema: Schema) -> dict[str, str]:
    return {"messages.hpp": generate_hpp(schema), "messages.py": generate_py(schema)}


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    default_out = Path(__file__).resolve().parent / "generated"
    parser.add_argument("--out-dir", type=Path, default=default_out)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if files on disk differ from what would be generated")
    args = parser.parse_args(argv[1:])

    try:
        schema = load_schema(*default_schema_paths())
    except SchemaError as exc:
        print(exc, file=sys.stderr)
        return 1

    rendered = render(schema)

    if args.check:
        stale = []
        for name, text in rendered.items():
            path = args.out_dir / name
            if not path.is_file() or path.read_text() != text:
                stale.append(str(path))
        if stale:
            print("generated files are stale or missing:\n  " + "\n  ".join(stale),
                  file=sys.stderr)
            return 1
        print("generated files are up to date")
        return 0

    args.out_dir.mkdir(parents=True, exist_ok=True)
    for name, text in rendered.items():
        (args.out_dir / name).write_text(text)
    print(f"generated {len(rendered)} file(s) into {args.out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
